load("@rules_cc//cc:defs.bzl", "cc_library")
load("//src:katara.bzl", "COPTS")

cc_library(
    name = "positions",
    srcs = ["positions.cc"],
    hdrs = ["positions.h"],
    copts = COPTS,
    visibility = [
        "//visibility:public",
    ],
)
